Repository ROCm/rocSPARSE, pull requests merged in 2024-10, with the labels that each got.

#411 Cherry-pick to docs/6.2.1: Expand the README note about the documentation (#857)
  README.md
Labels: documentation

#412 Cherry-pick to docs/6.2.0: Expand the README note about the documentation (#857)
  README.md
Labels: documentation

#410 Cherry-pick to docs/6.2.2: Expand the README note about the documentation (#857)
  README.md
Labels: documentation

#413 [Doc] Cherry pick - Bump rocm-docs-core from 1.8.1 to 1.8.2 in /docs/sphinx (#855)
  .readthedocs.yaml
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#409 Cherry-pick to release/rocm-rel-6.2: Expand the README note about the documentation (#857)
  README.md
Labels: documentation

#408 Cherry-pick to release-staging/rocm-rel-6.3: Expand the README note about the documentation (#857)
  README.md
Labels: documentation

#416 Cherry-pick to docs/6.2.2: Add missing metadata (#861)
  docs/license.rst
  docs/reference/api.rst
  docs/reference/reproducibility.rst
Labels: ci:docs-only

#415 Cherry-pick to release/rocm-rel-6.2: Add missing metadata (#861)
  docs/license.rst
  docs/reference/api.rst
  docs/reference/reproducibility.rst
Labels: ci:docs-only

#414 Cherry-pick to release-staging/rocm-rel-6.3: Add missing metadata (#861)
  docs/license.rst
  docs/reference/api.rst
  docs/reference/reproducibility.rst
Labels: ci:docs-only
